# Generated by Django 4.1.1 on 2022-09-17 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('customer', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SalesD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=20)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='inventory.item')),
                ('sales', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='inventory.sales')),
            ],
        ),
        migrations.RemoveField(
            model_name='selld',
            name='item',
        ),
        migrations.RemoveField(
            model_name='selld',
            name='sell',
        ),
        migrations.AddField(
            model_name='purchase',
            name='supplier',
            field=models.CharField(default='Test supplier', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='purchase',
            name='code',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='purchased',
            name='purchase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='inventory.purchase'),
        ),
        migrations.AlterField(
            model_name='purchased',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='purchased',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.DeleteModel(
            name='Sell',
        ),
        migrations.DeleteModel(
            name='SellD',
        ),
    ]
